# coding: utf-8

"""
    SuperMQ Users Service

    This is the Users Server based on the OpenAPI 3.0 specification.  It is the HTTP API for managing platform users. You can now help us improve the API whether it's by making changes to the definition itself or to the code. Some useful links: - [The SuperMQ repository](https://github.com/absmach/supermq)   # noqa: E501

    OpenAPI spec version: 0.18.0
    Contact: info@abstractmachines.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UsersPage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'users': 'list[User]',
        'total': 'int',
        'offset': 'int',
        'limit': 'int'
    }

    attribute_map = {
        'users': 'users',
        'total': 'total',
        'offset': 'offset',
        'limit': 'limit'
    }

    def __init__(self, users=None, total=None, offset=None, limit=None):  # noqa: E501
        """UsersPage - a model defined in Swagger"""  # noqa: E501
        self._users = None
        self._total = None
        self._offset = None
        self._limit = None
        self.discriminator = None
        self.users = users
        self.total = total
        if offset is not None:
            self.offset = offset
        self.limit = limit

    @property
    def users(self):
        """Gets the users of this UsersPage.  # noqa: E501


        :return: The users of this UsersPage.  # noqa: E501
        :rtype: list[User]
        """
        return self._users

    @users.setter
    def users(self, users):
        """Sets the users of this UsersPage.


        :param users: The users of this UsersPage.  # noqa: E501
        :type: list[User]
        """
        if users is None:
            raise ValueError("Invalid value for `users`, must not be `None`")  # noqa: E501

        self._users = users

    @property
    def total(self):
        """Gets the total of this UsersPage.  # noqa: E501

        Total number of items.  # noqa: E501

        :return: The total of this UsersPage.  # noqa: E501
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this UsersPage.

        Total number of items.  # noqa: E501

        :param total: The total of this UsersPage.  # noqa: E501
        :type: int
        """
        if total is None:
            raise ValueError("Invalid value for `total`, must not be `None`")  # noqa: E501

        self._total = total

    @property
    def offset(self):
        """Gets the offset of this UsersPage.  # noqa: E501

        Number of items to skip during retrieval.  # noqa: E501

        :return: The offset of this UsersPage.  # noqa: E501
        :rtype: int
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """Sets the offset of this UsersPage.

        Number of items to skip during retrieval.  # noqa: E501

        :param offset: The offset of this UsersPage.  # noqa: E501
        :type: int
        """

        self._offset = offset

    @property
    def limit(self):
        """Gets the limit of this UsersPage.  # noqa: E501

        Maximum number of items to return in one page.  # noqa: E501

        :return: The limit of this UsersPage.  # noqa: E501
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this UsersPage.

        Maximum number of items to return in one page.  # noqa: E501

        :param limit: The limit of this UsersPage.  # noqa: E501
        :type: int
        """
        if limit is None:
            raise ValueError("Invalid value for `limit`, must not be `None`")  # noqa: E501

        self._limit = limit

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UsersPage, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UsersPage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
