[metadata]
name = supermq-sdk
version = 0.18.2
author = SuperMQ Team
author_email = info@abstractmachines.fr
description = Python SDK for SuperMQ IoT Platform
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/absmach/supermq-sdk-py
project_urls =
    Bug Tracker = https://github.com/absmach/supermq-sdk-py/issues
    Documentation = https://github.com/absmach/supermq-sdk-py/tree/main/docs
    Source Code = https://github.com/absmach/supermq-sdk-py
classifiers =
    Development Status :: 4 - Beta
    Intended Audience :: Developers
    Topic :: Software Development :: Libraries :: Python Modules
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    License :: OSI Approved :: Apache Software License
    Operating System :: OS Independent

[options]
packages = find:
python_requires = >=3.9
include_package_data = True
install_requires =
    requests>=2.31.0
    urllib3>=1.26.0
    certifi>=2023.7.22
    python-dateutil>=2.8.2
    six>=1.16.0
