# coding: utf-8

"""
    SuperMQ Domains Service

    This is the Domains Server based on the OpenAPI 3.0 specification.  It is the HTTP API for managing platform domains. You can now help us improve the API whether it's by making changes to the definition itself or to the code. Some useful links: - [The SuperMQ repository](https://github.com/absmach/supermq)   # noqa: E501

    OpenAPI spec version: 0.18.0
    Contact: info@abstractmachines.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.invitations_api import InvitationsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestInvitationsApi(unittest.TestCase):
    """InvitationsApi unit test stubs"""

    def setUp(self):
        self.api = InvitationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_accept_invitation(self):
        """Test case for accept_invitation

        Accept invitation  # noqa: E501
        """
        pass

    def test_delete_invitation(self):
        """Test case for delete_invitation

        Deletes a specific invitation  # noqa: E501
        """
        pass

    def test_list_domain_invitations(self):
        """Test case for list_domain_invitations

        List domain invitations  # noqa: E501
        """
        pass

    def test_list_user_invitations(self):
        """Test case for list_user_invitations

        List user invitations  # noqa: E501
        """
        pass

    def test_reject_invitation(self):
        """Test case for reject_invitation

        Reject invitation  # noqa: E501
        """
        pass

    def test_send_invitation(self):
        """Test case for send_invitation

        Send invitation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
