# coding: utf-8

"""
    Magistrala reader service

    HTTP API for reading messages. Some useful links: - [The Magistrala repository](https://github.com/absmach/magistrala)   # noqa: E501

    OpenAPI spec version: 0.15.1
    Contact: info@abstractmachines.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.readers_api import ReadersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestReadersApi(unittest.TestCase):
    """ReadersApi unit test stubs"""

    def setUp(self):
        self.api = ReadersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_messages(self):
        """Test case for get_messages

        Retrieves messages sent to single channel  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
