# coding: utf-8

"""
    Magistrala reader service

    HTTP API for reading messages. Some useful links: - [The Magistrala repository](https://github.com/absmach/magistrala)   # noqa: E501

    OpenAPI spec version: 0.15.1
    Contact: info@abstractmachines.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.messages_page import MessagesPage  # noqa: E501
from swagger_client.rest import ApiException


class TestMessagesPage(unittest.TestCase):
    """MessagesPage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMessagesPage(self):
        """Test MessagesPage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.messages_page.MessagesPage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
