# coding: utf-8

"""
    Magistrala Reports Service API

    HTTP API for managing reports service.   # noqa: E501

    OpenAPI spec version: 0.15.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GenerateReportRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'action': 'str',
        'config_id': 'str',
        'name': 'str',
        'description': 'str',
        'schedule': 'Schedule',
        'config': 'MetricConfig',
        'email': 'EmailSetting',
        'metrics': 'list[ReqMetric]'
    }

    attribute_map = {
        'action': 'action',
        'config_id': 'config_id',
        'name': 'name',
        'description': 'description',
        'schedule': 'schedule',
        'config': 'config',
        'email': 'email',
        'metrics': 'metrics'
    }

    def __init__(self, action=None, config_id=None, name=None, description=None, schedule=None, config=None, email=None, metrics=None):  # noqa: E501
        """GenerateReportRequest - a model defined in Swagger"""  # noqa: E501
        self._action = None
        self._config_id = None
        self._name = None
        self._description = None
        self._schedule = None
        self._config = None
        self._email = None
        self._metrics = None
        self.discriminator = None
        self.action = action
        if config_id is not None:
            self.config_id = config_id
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if schedule is not None:
            self.schedule = schedule
        if config is not None:
            self.config = config
        if email is not None:
            self.email = email
        if metrics is not None:
            self.metrics = metrics

    @property
    def action(self):
        """Gets the action of this GenerateReportRequest.  # noqa: E501


        :return: The action of this GenerateReportRequest.  # noqa: E501
        :rtype: str
        """
        return self._action

    @action.setter
    def action(self, action):
        """Sets the action of this GenerateReportRequest.


        :param action: The action of this GenerateReportRequest.  # noqa: E501
        :type: str
        """
        if action is None:
            raise ValueError("Invalid value for `action`, must not be `None`")  # noqa: E501
        allowed_values = ["view", "download", "email"]  # noqa: E501
        if action not in allowed_values:
            raise ValueError(
                "Invalid value for `action` ({0}), must be one of {1}"  # noqa: E501
                .format(action, allowed_values)
            )

        self._action = action

    @property
    def config_id(self):
        """Gets the config_id of this GenerateReportRequest.  # noqa: E501


        :return: The config_id of this GenerateReportRequest.  # noqa: E501
        :rtype: str
        """
        return self._config_id

    @config_id.setter
    def config_id(self, config_id):
        """Sets the config_id of this GenerateReportRequest.


        :param config_id: The config_id of this GenerateReportRequest.  # noqa: E501
        :type: str
        """

        self._config_id = config_id

    @property
    def name(self):
        """Gets the name of this GenerateReportRequest.  # noqa: E501


        :return: The name of this GenerateReportRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this GenerateReportRequest.


        :param name: The name of this GenerateReportRequest.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this GenerateReportRequest.  # noqa: E501


        :return: The description of this GenerateReportRequest.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this GenerateReportRequest.


        :param description: The description of this GenerateReportRequest.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def schedule(self):
        """Gets the schedule of this GenerateReportRequest.  # noqa: E501


        :return: The schedule of this GenerateReportRequest.  # noqa: E501
        :rtype: Schedule
        """
        return self._schedule

    @schedule.setter
    def schedule(self, schedule):
        """Sets the schedule of this GenerateReportRequest.


        :param schedule: The schedule of this GenerateReportRequest.  # noqa: E501
        :type: Schedule
        """

        self._schedule = schedule

    @property
    def config(self):
        """Gets the config of this GenerateReportRequest.  # noqa: E501


        :return: The config of this GenerateReportRequest.  # noqa: E501
        :rtype: MetricConfig
        """
        return self._config

    @config.setter
    def config(self, config):
        """Sets the config of this GenerateReportRequest.


        :param config: The config of this GenerateReportRequest.  # noqa: E501
        :type: MetricConfig
        """

        self._config = config

    @property
    def email(self):
        """Gets the email of this GenerateReportRequest.  # noqa: E501


        :return: The email of this GenerateReportRequest.  # noqa: E501
        :rtype: EmailSetting
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this GenerateReportRequest.


        :param email: The email of this GenerateReportRequest.  # noqa: E501
        :type: EmailSetting
        """

        self._email = email

    @property
    def metrics(self):
        """Gets the metrics of this GenerateReportRequest.  # noqa: E501


        :return: The metrics of this GenerateReportRequest.  # noqa: E501
        :rtype: list[ReqMetric]
        """
        return self._metrics

    @metrics.setter
    def metrics(self, metrics):
        """Sets the metrics of this GenerateReportRequest.


        :param metrics: The metrics of this GenerateReportRequest.  # noqa: E501
        :type: list[ReqMetric]
        """

        self._metrics = metrics

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GenerateReportRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GenerateReportRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
