# coding: utf-8

"""
    Magistrala Reports Service API

    HTTP API for managing reports service.   # noqa: E501

    OpenAPI spec version: 0.15.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ReportConfig(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'description': 'str',
        'domain_id': 'str',
        'schedule': 'Schedule',
        'config': 'MetricConfig',
        'email': 'EmailSetting',
        'metrics': 'list[ReqMetric]',
        'status': 'Status',
        'created_at': 'datetime',
        'created_by': 'str',
        'updated_at': 'datetime',
        'updated_by': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'description': 'description',
        'domain_id': 'domain_id',
        'schedule': 'schedule',
        'config': 'config',
        'email': 'email',
        'metrics': 'metrics',
        'status': 'status',
        'created_at': 'created_at',
        'created_by': 'created_by',
        'updated_at': 'updated_at',
        'updated_by': 'updated_by'
    }

    def __init__(self, id=None, name=None, description=None, domain_id=None, schedule=None, config=None, email=None, metrics=None, status=None, created_at=None, created_by=None, updated_at=None, updated_by=None):  # noqa: E501
        """ReportConfig - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._description = None
        self._domain_id = None
        self._schedule = None
        self._config = None
        self._email = None
        self._metrics = None
        self._status = None
        self._created_at = None
        self._created_by = None
        self._updated_at = None
        self._updated_by = None
        self.discriminator = None
        if id is not None:
            self.id = id
        self.name = name
        if description is not None:
            self.description = description
        if domain_id is not None:
            self.domain_id = domain_id
        if schedule is not None:
            self.schedule = schedule
        self.config = config
        if email is not None:
            self.email = email
        self.metrics = metrics
        if status is not None:
            self.status = status
        if created_at is not None:
            self.created_at = created_at
        if created_by is not None:
            self.created_by = created_by
        if updated_at is not None:
            self.updated_at = updated_at
        if updated_by is not None:
            self.updated_by = updated_by

    @property
    def id(self):
        """Gets the id of this ReportConfig.  # noqa: E501


        :return: The id of this ReportConfig.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ReportConfig.


        :param id: The id of this ReportConfig.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this ReportConfig.  # noqa: E501


        :return: The name of this ReportConfig.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ReportConfig.


        :param name: The name of this ReportConfig.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this ReportConfig.  # noqa: E501


        :return: The description of this ReportConfig.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ReportConfig.


        :param description: The description of this ReportConfig.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def domain_id(self):
        """Gets the domain_id of this ReportConfig.  # noqa: E501


        :return: The domain_id of this ReportConfig.  # noqa: E501
        :rtype: str
        """
        return self._domain_id

    @domain_id.setter
    def domain_id(self, domain_id):
        """Sets the domain_id of this ReportConfig.


        :param domain_id: The domain_id of this ReportConfig.  # noqa: E501
        :type: str
        """

        self._domain_id = domain_id

    @property
    def schedule(self):
        """Gets the schedule of this ReportConfig.  # noqa: E501


        :return: The schedule of this ReportConfig.  # noqa: E501
        :rtype: Schedule
        """
        return self._schedule

    @schedule.setter
    def schedule(self, schedule):
        """Sets the schedule of this ReportConfig.


        :param schedule: The schedule of this ReportConfig.  # noqa: E501
        :type: Schedule
        """

        self._schedule = schedule

    @property
    def config(self):
        """Gets the config of this ReportConfig.  # noqa: E501


        :return: The config of this ReportConfig.  # noqa: E501
        :rtype: MetricConfig
        """
        return self._config

    @config.setter
    def config(self, config):
        """Sets the config of this ReportConfig.


        :param config: The config of this ReportConfig.  # noqa: E501
        :type: MetricConfig
        """
        if config is None:
            raise ValueError("Invalid value for `config`, must not be `None`")  # noqa: E501

        self._config = config

    @property
    def email(self):
        """Gets the email of this ReportConfig.  # noqa: E501


        :return: The email of this ReportConfig.  # noqa: E501
        :rtype: EmailSetting
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this ReportConfig.


        :param email: The email of this ReportConfig.  # noqa: E501
        :type: EmailSetting
        """

        self._email = email

    @property
    def metrics(self):
        """Gets the metrics of this ReportConfig.  # noqa: E501


        :return: The metrics of this ReportConfig.  # noqa: E501
        :rtype: list[ReqMetric]
        """
        return self._metrics

    @metrics.setter
    def metrics(self, metrics):
        """Sets the metrics of this ReportConfig.


        :param metrics: The metrics of this ReportConfig.  # noqa: E501
        :type: list[ReqMetric]
        """
        if metrics is None:
            raise ValueError("Invalid value for `metrics`, must not be `None`")  # noqa: E501

        self._metrics = metrics

    @property
    def status(self):
        """Gets the status of this ReportConfig.  # noqa: E501


        :return: The status of this ReportConfig.  # noqa: E501
        :rtype: Status
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ReportConfig.


        :param status: The status of this ReportConfig.  # noqa: E501
        :type: Status
        """

        self._status = status

    @property
    def created_at(self):
        """Gets the created_at of this ReportConfig.  # noqa: E501


        :return: The created_at of this ReportConfig.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this ReportConfig.


        :param created_at: The created_at of this ReportConfig.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def created_by(self):
        """Gets the created_by of this ReportConfig.  # noqa: E501


        :return: The created_by of this ReportConfig.  # noqa: E501
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this ReportConfig.


        :param created_by: The created_by of this ReportConfig.  # noqa: E501
        :type: str
        """

        self._created_by = created_by

    @property
    def updated_at(self):
        """Gets the updated_at of this ReportConfig.  # noqa: E501


        :return: The updated_at of this ReportConfig.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this ReportConfig.


        :param updated_at: The updated_at of this ReportConfig.  # noqa: E501
        :type: datetime
        """

        self._updated_at = updated_at

    @property
    def updated_by(self):
        """Gets the updated_by of this ReportConfig.  # noqa: E501


        :return: The updated_by of this ReportConfig.  # noqa: E501
        :rtype: str
        """
        return self._updated_by

    @updated_by.setter
    def updated_by(self, updated_by):
        """Sets the updated_by of this ReportConfig.


        :param updated_by: The updated_by of this ReportConfig.  # noqa: E501
        :type: str
        """

        self._updated_by = updated_by

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ReportConfig, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReportConfig):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
