# coding: utf-8

"""
    Magistrala Reports Service API

    HTTP API for managing reports service.   # noqa: E501

    OpenAPI spec version: 0.15.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.metric_config import MetricConfig  # noqa: E501
from swagger_client.rest import ApiException


class TestMetricConfig(unittest.TestCase):
    """MetricConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetricConfig(self):
        """Test MetricConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.metric_config.MetricConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
