# coding: utf-8

"""
    Magistrala Reports Service API

    HTTP API for managing reports service.   # noqa: E501

    OpenAPI spec version: 0.15.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.reports_api import ReportsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestReportsApi(unittest.TestCase):
    """ReportsApi unit test stubs"""

    def setUp(self):
        self.api = ReportsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_report_config(self):
        """Test case for add_report_config

        Create a report configuration  # noqa: E501
        """
        pass

    def test_delete_report_config(self):
        """Test case for delete_report_config

        Delete a report configuration  # noqa: E501
        """
        pass

    def test_disable_report_config(self):
        """Test case for disable_report_config

        Disable a report configuration  # noqa: E501
        """
        pass

    def test_enable_report_config(self):
        """Test case for enable_report_config

        Enable a report configuration  # noqa: E501
        """
        pass

    def test_generate_report(self):
        """Test case for generate_report

        Generate a report  # noqa: E501
        """
        pass

    def test_list_report_configs(self):
        """Test case for list_report_configs

        List report configurations  # noqa: E501
        """
        pass

    def test_update_report_config(self):
        """Test case for update_report_config

        Update a report configuration  # noqa: E501
        """
        pass

    def test_update_report_schedule(self):
        """Test case for update_report_schedule

        Update report schedule  # noqa: E501
        """
        pass

    def test_view_report_config(self):
        """Test case for view_report_config

        View a report configuration  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
