# coding: utf-8

"""
    SuperMQ Groups Service

    This is the Groups Server based on the OpenAPI 3.0 specification.  It is the HTTP API for managing platform groups. You can now help us improve the API whether it's by making changes to the definition itself or to the code. Some useful links: - [The SuperMQ repository](https://github.com/absmach/supermq)   # noqa: E501

    OpenAPI spec version: 0.18.0
    Contact: info@abstractmachines.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CreateRoleObj(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'role_name': 'str',
        'optional_actions': 'list[str]',
        'optional_members': 'list[str]'
    }

    attribute_map = {
        'role_name': 'role_name',
        'optional_actions': 'optional_actions',
        'optional_members': 'optional_members'
    }

    def __init__(self, role_name=None, optional_actions=None, optional_members=None):  # noqa: E501
        """CreateRoleObj - a model defined in Swagger"""  # noqa: E501
        self._role_name = None
        self._optional_actions = None
        self._optional_members = None
        self.discriminator = None
        if role_name is not None:
            self.role_name = role_name
        if optional_actions is not None:
            self.optional_actions = optional_actions
        if optional_members is not None:
            self.optional_members = optional_members

    @property
    def role_name(self):
        """Gets the role_name of this CreateRoleObj.  # noqa: E501

        Role's name.  # noqa: E501

        :return: The role_name of this CreateRoleObj.  # noqa: E501
        :rtype: str
        """
        return self._role_name

    @role_name.setter
    def role_name(self, role_name):
        """Sets the role_name of this CreateRoleObj.

        Role's name.  # noqa: E501

        :param role_name: The role_name of this CreateRoleObj.  # noqa: E501
        :type: str
        """

        self._role_name = role_name

    @property
    def optional_actions(self):
        """Gets the optional_actions of this CreateRoleObj.  # noqa: E501

        List of optional actions.  # noqa: E501

        :return: The optional_actions of this CreateRoleObj.  # noqa: E501
        :rtype: list[str]
        """
        return self._optional_actions

    @optional_actions.setter
    def optional_actions(self, optional_actions):
        """Sets the optional_actions of this CreateRoleObj.

        List of optional actions.  # noqa: E501

        :param optional_actions: The optional_actions of this CreateRoleObj.  # noqa: E501
        :type: list[str]
        """

        self._optional_actions = optional_actions

    @property
    def optional_members(self):
        """Gets the optional_members of this CreateRoleObj.  # noqa: E501

        List of optional members.  # noqa: E501

        :return: The optional_members of this CreateRoleObj.  # noqa: E501
        :rtype: list[str]
        """
        return self._optional_members

    @optional_members.setter
    def optional_members(self, optional_members):
        """Sets the optional_members of this CreateRoleObj.

        List of optional members.  # noqa: E501

        :param optional_members: The optional_members of this CreateRoleObj.  # noqa: E501
        :type: list[str]
        """

        self._optional_members = optional_members

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateRoleObj, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateRoleObj):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
