# coding: utf-8

"""
    SuperMQ Groups Service

    This is the Groups Server based on the OpenAPI 3.0 specification.  It is the HTTP API for managing platform groups. You can now help us improve the API whether it's by making changes to the definition itself or to the code. Some useful links: - [The SuperMQ repository](https://github.com/absmach/supermq)   # noqa: E501

    OpenAPI spec version: 0.18.0
    Contact: info@abstractmachines.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GroupsHierarchyPage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'level': 'int',
        'direction': 'int',
        'groups': 'list[Group]'
    }

    attribute_map = {
        'level': 'level',
        'direction': 'direction',
        'groups': 'groups'
    }

    def __init__(self, level=None, direction=None, groups=None):  # noqa: E501
        """GroupsHierarchyPage - a model defined in Swagger"""  # noqa: E501
        self._level = None
        self._direction = None
        self._groups = None
        self.discriminator = None
        if level is not None:
            self.level = level
        if direction is not None:
            self.direction = direction
        if groups is not None:
            self.groups = groups

    @property
    def level(self):
        """Gets the level of this GroupsHierarchyPage.  # noqa: E501

        Level of hierarchy.  # noqa: E501

        :return: The level of this GroupsHierarchyPage.  # noqa: E501
        :rtype: int
        """
        return self._level

    @level.setter
    def level(self, level):
        """Sets the level of this GroupsHierarchyPage.

        Level of hierarchy.  # noqa: E501

        :param level: The level of this GroupsHierarchyPage.  # noqa: E501
        :type: int
        """

        self._level = level

    @property
    def direction(self):
        """Gets the direction of this GroupsHierarchyPage.  # noqa: E501

        Direction of hierarchy traversal.  # noqa: E501

        :return: The direction of this GroupsHierarchyPage.  # noqa: E501
        :rtype: int
        """
        return self._direction

    @direction.setter
    def direction(self, direction):
        """Sets the direction of this GroupsHierarchyPage.

        Direction of hierarchy traversal.  # noqa: E501

        :param direction: The direction of this GroupsHierarchyPage.  # noqa: E501
        :type: int
        """

        self._direction = direction

    @property
    def groups(self):
        """Gets the groups of this GroupsHierarchyPage.  # noqa: E501


        :return: The groups of this GroupsHierarchyPage.  # noqa: E501
        :rtype: list[Group]
        """
        return self._groups

    @groups.setter
    def groups(self, groups):
        """Sets the groups of this GroupsHierarchyPage.


        :param groups: The groups of this GroupsHierarchyPage.  # noqa: E501
        :type: list[Group]
        """

        self._groups = groups

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GroupsHierarchyPage, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GroupsHierarchyPage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
