# coding: utf-8

"""
    SuperMQ Groups Service

    This is the Groups Server based on the OpenAPI 3.0 specification.  It is the HTTP API for managing platform groups. You can now help us improve the API whether it's by making changes to the definition itself or to the code. Some useful links: - [The SuperMQ repository](https://github.com/absmach/supermq)   # noqa: E501

    OpenAPI spec version: 0.18.0
    Contact: info@abstractmachines.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.roles_api import RolesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRolesApi(unittest.TestCase):
    """RolesApi unit test stubs"""

    def setUp(self):
        self.api = RolesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_group_role_action(self):
        """Test case for add_group_role_action

        Adds a role action for a group role.  # noqa: E501
        """
        pass

    def test_add_group_role_member(self):
        """Test case for add_group_role_member

        Adds a member to a group role.  # noqa: E501
        """
        pass

    def test_create_group_role(self):
        """Test case for create_group_role

        Creates a role for a group  # noqa: E501
        """
        pass

    def test_delete_all_group_role_actions(self):
        """Test case for delete_all_group_role_actions

        Deletes all role actions for a group role.  # noqa: E501
        """
        pass

    def test_delete_all_group_role_members(self):
        """Test case for delete_all_group_role_members

        Deletes all members from a group role.  # noqa: E501
        """
        pass

    def test_delete_group_role(self):
        """Test case for delete_group_role

        Deletes group role.  # noqa: E501
        """
        pass

    def test_delete_group_role_action(self):
        """Test case for delete_group_role_action

        Deletes role actions for a group role.  # noqa: E501
        """
        pass

    def test_delete_group_role_members(self):
        """Test case for delete_group_role_members

        Deletes members from a group role.  # noqa: E501
        """
        pass

    def test_get_group_members(self):
        """Test case for get_group_members

        Retrieves group members from all roles.  # noqa: E501
        """
        pass

    def test_get_group_role(self):
        """Test case for get_group_role

        Retrieves group role.  # noqa: E501
        """
        pass

    def test_list_available_actions(self):
        """Test case for list_available_actions

        Retrieves available actions.  # noqa: E501
        """
        pass

    def test_list_group_role_actions(self):
        """Test case for list_group_role_actions

        Lists group role actions.  # noqa: E501
        """
        pass

    def test_list_group_role_members(self):
        """Test case for list_group_role_members

        Lists group role members.  # noqa: E501
        """
        pass

    def test_list_group_roles(self):
        """Test case for list_group_roles

        Retrieves groups roles.  # noqa: E501
        """
        pass

    def test_update_group_role(self):
        """Test case for update_group_role

        Updates group role.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
