# coding: utf-8

"""
    Magistrala Notifiers service

    HTTP API for Notifiers service. Some useful links: - [The Magistrala repository](https://github.com/absmach/magistrala)   # noqa: E501

    OpenAPI spec version: 0.15.1
    Contact: info@abstractmachines.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Subscription(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'owner_id': 'str',
        'topic': 'str',
        'contact': 'str'
    }

    attribute_map = {
        'id': 'id',
        'owner_id': 'owner_id',
        'topic': 'topic',
        'contact': 'contact'
    }

    def __init__(self, id=None, owner_id=None, topic=None, contact=None):  # noqa: E501
        """Subscription - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._owner_id = None
        self._topic = None
        self._contact = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if owner_id is not None:
            self.owner_id = owner_id
        if topic is not None:
            self.topic = topic
        if contact is not None:
            self.contact = contact

    @property
    def id(self):
        """Gets the id of this Subscription.  # noqa: E501

        ULID id of the subscription.  # noqa: E501

        :return: The id of this Subscription.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Subscription.

        ULID id of the subscription.  # noqa: E501

        :param id: The id of this Subscription.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def owner_id(self):
        """Gets the owner_id of this Subscription.  # noqa: E501

        An id of the owner who created subscription.  # noqa: E501

        :return: The owner_id of this Subscription.  # noqa: E501
        :rtype: str
        """
        return self._owner_id

    @owner_id.setter
    def owner_id(self, owner_id):
        """Sets the owner_id of this Subscription.

        An id of the owner who created subscription.  # noqa: E501

        :param owner_id: The owner_id of this Subscription.  # noqa: E501
        :type: str
        """

        self._owner_id = owner_id

    @property
    def topic(self):
        """Gets the topic of this Subscription.  # noqa: E501

        Topic to which the user subscribes.  # noqa: E501

        :return: The topic of this Subscription.  # noqa: E501
        :rtype: str
        """
        return self._topic

    @topic.setter
    def topic(self, topic):
        """Sets the topic of this Subscription.

        Topic to which the user subscribes.  # noqa: E501

        :param topic: The topic of this Subscription.  # noqa: E501
        :type: str
        """

        self._topic = topic

    @property
    def contact(self):
        """Gets the contact of this Subscription.  # noqa: E501

        The contact of the user to which the notification will be sent.  # noqa: E501

        :return: The contact of this Subscription.  # noqa: E501
        :rtype: str
        """
        return self._contact

    @contact.setter
    def contact(self, contact):
        """Sets the contact of this Subscription.

        The contact of the user to which the notification will be sent.  # noqa: E501

        :param contact: The contact of this Subscription.  # noqa: E501
        :type: str
        """

        self._contact = contact

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Subscription, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Subscription):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
