# coding: utf-8

"""
    SuperMQ Channels Service

    This is the Channels Server based on the OpenAPI 3.0 specification.  It is the HTTP API for managing platform channels. You can now help us improve the API whether it's by making changes to the definition itself or to the code. Some useful links: - [The SuperMQ repository](https://github.com/absmach/supermq)   # noqa: E501

    OpenAPI spec version: 0.18.0
    Contact: info@abstractmachines.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.channel_req_obj import ChannelReqObj  # noqa: E501
from swagger_client.rest import ApiException


class TestChannelReqObj(unittest.TestCase):
    """ChannelReqObj unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChannelReqObj(self):
        """Test ChannelReqObj"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.channel_req_obj.ChannelReqObj()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
