# coding: utf-8

"""
    SuperMQ http adapter

    HTTP API for sending messages through communication channels. Some useful links: - [The SuperMQ repository](https://github.com/absmach/supermq)   # noqa: E501

    OpenAPI spec version: 0.18.0
    Contact: info@abstractmachines.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.sen_ml_record import SenMLRecord  # noqa: E501
from swagger_client.rest import ApiException


class TestSenMLRecord(unittest.TestCase):
    """SenMLRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSenMLRecord(self):
        """Test SenMLRecord"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.sen_ml_record.SenMLRecord()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
