# coding: utf-8

"""
    SuperMQ http adapter

    HTTP API for sending messages through communication channels. Some useful links: - [The SuperMQ repository](https://github.com/absmach/supermq)   # noqa: E501

    OpenAPI spec version: 0.18.0
    Contact: info@abstractmachines.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.health_api import HealthApi  # noqa: E501
from swagger_client.rest import ApiException


class TestHealthApi(unittest.TestCase):
    """HealthApi unit test stubs"""

    def setUp(self):
        self.api = HealthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_health_get(self):
        """Test case for health_get

        Retrieves service health check info.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
