# coding: utf-8

"""
    Magistrala Alarms API

    HTTP API for managing alarms service. Some useful links: - [The Magistrala repository](https://github.com/absmach/magistrala)   # noqa: E501

    OpenAPI spec version: 0.15.1
    Contact: info@abstractmachines.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.alarms_api import AlarmsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAlarmsApi(unittest.TestCase):
    """AlarmsApi unit test stubs"""

    def setUp(self):
        self.api = AlarmsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_alarm(self):
        """Test case for delete_alarm

        Delete Alarm  # noqa: E501
        """
        pass

    def test_list_alarms(self):
        """Test case for list_alarms

        List Alarms  # noqa: E501
        """
        pass

    def test_update_alarm(self):
        """Test case for update_alarm

        Update Alarm  # noqa: E501
        """
        pass

    def test_view_alarm(self):
        """Test case for view_alarm

        View Alarm  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
