# coding: utf-8

"""
    SuperMQ Groups Service

    This is the Groups Server based on the OpenAPI 3.0 specification.  It is the HTTP API for managing platform groups. You can now help us improve the API whether it's by making changes to the definition itself or to the code. Some useful links: - [The SuperMQ repository](https://github.com/absmach/supermq)   # noqa: E501

    OpenAPI spec version: 0.18.0
    Contact: info@abstractmachines.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class RolesApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def add_group_role_action(self, body, domain_id, group_id, **kwargs):  # noqa: E501
        """Adds a role action for a group role.  # noqa: E501

        Adds a role action for a specific group role that is identified by the role name.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.add_group_role_action(body, domain_id, group_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param RoleActionsObj body: JSON- formatted object decsribing an action to be added to a role. (required)
        :param str domain_id: Unique domain identifier. (required)
        :param str group_id: Unique group identifier. (required)
        :param str role_id: List groups that the user has the given role ID on.
        :return: RoleActionsObj
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.add_group_role_action_with_http_info(body, domain_id, group_id, **kwargs)  # noqa: E501
        else:
            (data) = self.add_group_role_action_with_http_info(body, domain_id, group_id, **kwargs)  # noqa: E501
            return data

    def add_group_role_action_with_http_info(self, body, domain_id, group_id, **kwargs):  # noqa: E501
        """Adds a role action for a group role.  # noqa: E501

        Adds a role action for a specific group role that is identified by the role name.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.add_group_role_action_with_http_info(body, domain_id, group_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param RoleActionsObj body: JSON- formatted object decsribing an action to be added to a role. (required)
        :param str domain_id: Unique domain identifier. (required)
        :param str group_id: Unique group identifier. (required)
        :param str role_id: List groups that the user has the given role ID on.
        :return: RoleActionsObj
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'domain_id', 'group_id', 'role_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method add_group_role_action" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `add_group_role_action`")  # noqa: E501
        # verify the required parameter 'domain_id' is set
        if ('domain_id' not in params or
                params['domain_id'] is None):
            raise ValueError("Missing the required parameter `domain_id` when calling `add_group_role_action`")  # noqa: E501
        # verify the required parameter 'group_id' is set
        if ('group_id' not in params or
                params['group_id'] is None):
            raise ValueError("Missing the required parameter `group_id` when calling `add_group_role_action`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'domain_id' in params:
            path_params['domainID'] = params['domain_id']  # noqa: E501
        if 'group_id' in params:
            path_params['groupID'] = params['group_id']  # noqa: E501

        query_params = []
        if 'role_id' in params:
            query_params.append(('role_id', params['role_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/{domainID}/groups/{groupID}/roles/{roleID}/actions', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='RoleActionsObj',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def add_group_role_member(self, body, domain_id, group_id, **kwargs):  # noqa: E501
        """Adds a member to a group role.  # noqa: E501

        Adds a member to a specific group role that is identified by the role name.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.add_group_role_member(body, domain_id, group_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param RoleMembersObj body: JSON- formatted object decsribing a member to be added to a role. (required)
        :param str domain_id: Unique domain identifier. (required)
        :param str group_id: Unique group identifier. (required)
        :param str role_id: List groups that the user has the given role ID on.
        :return: RoleMembersObj
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.add_group_role_member_with_http_info(body, domain_id, group_id, **kwargs)  # noqa: E501
        else:
            (data) = self.add_group_role_member_with_http_info(body, domain_id, group_id, **kwargs)  # noqa: E501
            return data

    def add_group_role_member_with_http_info(self, body, domain_id, group_id, **kwargs):  # noqa: E501
        """Adds a member to a group role.  # noqa: E501

        Adds a member to a specific group role that is identified by the role name.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.add_group_role_member_with_http_info(body, domain_id, group_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param RoleMembersObj body: JSON- formatted object decsribing a member to be added to a role. (required)
        :param str domain_id: Unique domain identifier. (required)
        :param str group_id: Unique group identifier. (required)
        :param str role_id: List groups that the user has the given role ID on.
        :return: RoleMembersObj
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'domain_id', 'group_id', 'role_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method add_group_role_member" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `add_group_role_member`")  # noqa: E501
        # verify the required parameter 'domain_id' is set
        if ('domain_id' not in params or
                params['domain_id'] is None):
            raise ValueError("Missing the required parameter `domain_id` when calling `add_group_role_member`")  # noqa: E501
        # verify the required parameter 'group_id' is set
        if ('group_id' not in params or
                params['group_id'] is None):
            raise ValueError("Missing the required parameter `group_id` when calling `add_group_role_member`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'domain_id' in params:
            path_params['domainID'] = params['domain_id']  # noqa: E501
        if 'group_id' in params:
            path_params['groupID'] = params['group_id']  # noqa: E501

        query_params = []
        if 'role_id' in params:
            query_params.append(('role_id', params['role_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/{domainID}/groups/{groupID}/roles/{roleID}/members', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='RoleMembersObj',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def create_group_role(self, body, domain_id, group_id, **kwargs):  # noqa: E501
        """Creates a role for a group  # noqa: E501

        Creates a role for a specific group that is identified by the group ID.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_group_role(body, domain_id, group_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param CreateRoleObj body: JSON- formatted object decsribing a new role to be created. (required)
        :param str domain_id: Unique domain identifier. (required)
        :param str group_id: Unique group identifier. (required)
        :return: NewRole
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_group_role_with_http_info(body, domain_id, group_id, **kwargs)  # noqa: E501
        else:
            (data) = self.create_group_role_with_http_info(body, domain_id, group_id, **kwargs)  # noqa: E501
            return data

    def create_group_role_with_http_info(self, body, domain_id, group_id, **kwargs):  # noqa: E501
        """Creates a role for a group  # noqa: E501

        Creates a role for a specific group that is identified by the group ID.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_group_role_with_http_info(body, domain_id, group_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param CreateRoleObj body: JSON- formatted object decsribing a new role to be created. (required)
        :param str domain_id: Unique domain identifier. (required)
        :param str group_id: Unique group identifier. (required)
        :return: NewRole
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'domain_id', 'group_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_group_role" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `create_group_role`")  # noqa: E501
        # verify the required parameter 'domain_id' is set
        if ('domain_id' not in params or
                params['domain_id'] is None):
            raise ValueError("Missing the required parameter `domain_id` when calling `create_group_role`")  # noqa: E501
        # verify the required parameter 'group_id' is set
        if ('group_id' not in params or
                params['group_id'] is None):
            raise ValueError("Missing the required parameter `group_id` when calling `create_group_role`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'domain_id' in params:
            path_params['domainID'] = params['domain_id']  # noqa: E501
        if 'group_id' in params:
            path_params['groupID'] = params['group_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/{domainID}/groups/{groupID}/roles', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='NewRole',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_all_group_role_actions(self, domain_id, group_id, **kwargs):  # noqa: E501
        """Deletes all role actions for a group role.  # noqa: E501

        Deletes all role actions for a specific group role that is identified by the role name.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_all_group_role_actions(domain_id, group_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str domain_id: Unique domain identifier. (required)
        :param str group_id: Unique group identifier. (required)
        :param str role_id: List groups that the user has the given role ID on.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_all_group_role_actions_with_http_info(domain_id, group_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_all_group_role_actions_with_http_info(domain_id, group_id, **kwargs)  # noqa: E501
            return data

    def delete_all_group_role_actions_with_http_info(self, domain_id, group_id, **kwargs):  # noqa: E501
        """Deletes all role actions for a group role.  # noqa: E501

        Deletes all role actions for a specific group role that is identified by the role name.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_all_group_role_actions_with_http_info(domain_id, group_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str domain_id: Unique domain identifier. (required)
        :param str group_id: Unique group identifier. (required)
        :param str role_id: List groups that the user has the given role ID on.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['domain_id', 'group_id', 'role_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_all_group_role_actions" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'domain_id' is set
        if ('domain_id' not in params or
                params['domain_id'] is None):
            raise ValueError("Missing the required parameter `domain_id` when calling `delete_all_group_role_actions`")  # noqa: E501
        # verify the required parameter 'group_id' is set
        if ('group_id' not in params or
                params['group_id'] is None):
            raise ValueError("Missing the required parameter `group_id` when calling `delete_all_group_role_actions`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'domain_id' in params:
            path_params['domainID'] = params['domain_id']  # noqa: E501
        if 'group_id' in params:
            path_params['groupID'] = params['group_id']  # noqa: E501

        query_params = []
        if 'role_id' in params:
            query_params.append(('role_id', params['role_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/{domainID}/groups/{groupID}/roles/{roleID}/actions/delete-all', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_all_group_role_members(self, domain_id, group_id, **kwargs):  # noqa: E501
        """Deletes all members from a group role.  # noqa: E501

        Deletes all members from a specific group role that is identified by the role name.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_all_group_role_members(domain_id, group_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str domain_id: Unique domain identifier. (required)
        :param str group_id: Unique group identifier. (required)
        :param str role_id: List groups that the user has the given role ID on.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_all_group_role_members_with_http_info(domain_id, group_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_all_group_role_members_with_http_info(domain_id, group_id, **kwargs)  # noqa: E501
            return data

    def delete_all_group_role_members_with_http_info(self, domain_id, group_id, **kwargs):  # noqa: E501
        """Deletes all members from a group role.  # noqa: E501

        Deletes all members from a specific group role that is identified by the role name.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_all_group_role_members_with_http_info(domain_id, group_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str domain_id: Unique domain identifier. (required)
        :param str group_id: Unique group identifier. (required)
        :param str role_id: List groups that the user has the given role ID on.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['domain_id', 'group_id', 'role_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_all_group_role_members" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'domain_id' is set
        if ('domain_id' not in params or
                params['domain_id'] is None):
            raise ValueError("Missing the required parameter `domain_id` when calling `delete_all_group_role_members`")  # noqa: E501
        # verify the required parameter 'group_id' is set
        if ('group_id' not in params or
                params['group_id'] is None):
            raise ValueError("Missing the required parameter `group_id` when calling `delete_all_group_role_members`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'domain_id' in params:
            path_params['domainID'] = params['domain_id']  # noqa: E501
        if 'group_id' in params:
            path_params['groupID'] = params['group_id']  # noqa: E501

        query_params = []
        if 'role_id' in params:
            query_params.append(('role_id', params['role_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/{domainID}/groups/{groupID}/roles/{roleID}/members/delete-all', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_group_role(self, domain_id, group_id, **kwargs):  # noqa: E501
        """Deletes group role.  # noqa: E501

        Deletes a specific group role that is identifier by the role name.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_group_role(domain_id, group_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str domain_id: Unique domain identifier. (required)
        :param str group_id: Unique group identifier. (required)
        :param str role_id: List groups that the user has the given role ID on.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_group_role_with_http_info(domain_id, group_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_group_role_with_http_info(domain_id, group_id, **kwargs)  # noqa: E501
            return data

    def delete_group_role_with_http_info(self, domain_id, group_id, **kwargs):  # noqa: E501
        """Deletes group role.  # noqa: E501

        Deletes a specific group role that is identifier by the role name.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_group_role_with_http_info(domain_id, group_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str domain_id: Unique domain identifier. (required)
        :param str group_id: Unique group identifier. (required)
        :param str role_id: List groups that the user has the given role ID on.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['domain_id', 'group_id', 'role_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_group_role" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'domain_id' is set
        if ('domain_id' not in params or
                params['domain_id'] is None):
            raise ValueError("Missing the required parameter `domain_id` when calling `delete_group_role`")  # noqa: E501
        # verify the required parameter 'group_id' is set
        if ('group_id' not in params or
                params['group_id'] is None):
            raise ValueError("Missing the required parameter `group_id` when calling `delete_group_role`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'domain_id' in params:
            path_params['domainID'] = params['domain_id']  # noqa: E501
        if 'group_id' in params:
            path_params['groupID'] = params['group_id']  # noqa: E501

        query_params = []
        if 'role_id' in params:
            query_params.append(('role_id', params['role_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/{domainID}/groups/{groupID}/roles/{roleID}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_group_role_action(self, body, domain_id, group_id, **kwargs):  # noqa: E501
        """Deletes role actions for a group role.  # noqa: E501

        Deletes a role action for a specific group role that is identified by the role name.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_group_role_action(body, domain_id, group_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param RoleActionsObj body: JSON- formatted object decsribing an action to be added to a role. (required)
        :param str domain_id: Unique domain identifier. (required)
        :param str group_id: Unique group identifier. (required)
        :param str role_id: List groups that the user has the given role ID on.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_group_role_action_with_http_info(body, domain_id, group_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_group_role_action_with_http_info(body, domain_id, group_id, **kwargs)  # noqa: E501
            return data

    def delete_group_role_action_with_http_info(self, body, domain_id, group_id, **kwargs):  # noqa: E501
        """Deletes role actions for a group role.  # noqa: E501

        Deletes a role action for a specific group role that is identified by the role name.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_group_role_action_with_http_info(body, domain_id, group_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param RoleActionsObj body: JSON- formatted object decsribing an action to be added to a role. (required)
        :param str domain_id: Unique domain identifier. (required)
        :param str group_id: Unique group identifier. (required)
        :param str role_id: List groups that the user has the given role ID on.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'domain_id', 'group_id', 'role_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_group_role_action" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `delete_group_role_action`")  # noqa: E501
        # verify the required parameter 'domain_id' is set
        if ('domain_id' not in params or
                params['domain_id'] is None):
            raise ValueError("Missing the required parameter `domain_id` when calling `delete_group_role_action`")  # noqa: E501
        # verify the required parameter 'group_id' is set
        if ('group_id' not in params or
                params['group_id'] is None):
            raise ValueError("Missing the required parameter `group_id` when calling `delete_group_role_action`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'domain_id' in params:
            path_params['domainID'] = params['domain_id']  # noqa: E501
        if 'group_id' in params:
            path_params['groupID'] = params['group_id']  # noqa: E501

        query_params = []
        if 'role_id' in params:
            query_params.append(('role_id', params['role_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/{domainID}/groups/{groupID}/roles/{roleID}/actions/delete', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_group_role_members(self, body, domain_id, group_id, **kwargs):  # noqa: E501
        """Deletes members from a group role.  # noqa: E501

        Deletes a member from a specific group role that is identified by the role name.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_group_role_members(body, domain_id, group_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param RoleMembersObj body: JSON- formatted object decsribing a member to be added to a role. (required)
        :param str domain_id: Unique domain identifier. (required)
        :param str group_id: Unique group identifier. (required)
        :param str role_id: List groups that the user has the given role ID on.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_group_role_members_with_http_info(body, domain_id, group_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_group_role_members_with_http_info(body, domain_id, group_id, **kwargs)  # noqa: E501
            return data

    def delete_group_role_members_with_http_info(self, body, domain_id, group_id, **kwargs):  # noqa: E501
        """Deletes members from a group role.  # noqa: E501

        Deletes a member from a specific group role that is identified by the role name.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_group_role_members_with_http_info(body, domain_id, group_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param RoleMembersObj body: JSON- formatted object decsribing a member to be added to a role. (required)
        :param str domain_id: Unique domain identifier. (required)
        :param str group_id: Unique group identifier. (required)
        :param str role_id: List groups that the user has the given role ID on.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'domain_id', 'group_id', 'role_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_group_role_members" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `delete_group_role_members`")  # noqa: E501
        # verify the required parameter 'domain_id' is set
        if ('domain_id' not in params or
                params['domain_id'] is None):
            raise ValueError("Missing the required parameter `domain_id` when calling `delete_group_role_members`")  # noqa: E501
        # verify the required parameter 'group_id' is set
        if ('group_id' not in params or
                params['group_id'] is None):
            raise ValueError("Missing the required parameter `group_id` when calling `delete_group_role_members`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'domain_id' in params:
            path_params['domainID'] = params['domain_id']  # noqa: E501
        if 'group_id' in params:
            path_params['groupID'] = params['group_id']  # noqa: E501

        query_params = []
        if 'role_id' in params:
            query_params.append(('role_id', params['role_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/{domainID}/groups/{groupID}/roles/{roleID}/members/delete', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_group_members(self, domain_id, group_id, **kwargs):  # noqa: E501
        """Retrieves group members from all roles.  # noqa: E501

        Retrieves members from role for the specific group.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_group_members(domain_id, group_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str domain_id: Unique domain identifier. (required)
        :param str group_id: Unique group identifier. (required)
        :return: EntityMembersObj
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_group_members_with_http_info(domain_id, group_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_group_members_with_http_info(domain_id, group_id, **kwargs)  # noqa: E501
            return data

    def get_group_members_with_http_info(self, domain_id, group_id, **kwargs):  # noqa: E501
        """Retrieves group members from all roles.  # noqa: E501

        Retrieves members from role for the specific group.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_group_members_with_http_info(domain_id, group_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str domain_id: Unique domain identifier. (required)
        :param str group_id: Unique group identifier. (required)
        :return: EntityMembersObj
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['domain_id', 'group_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_group_members" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'domain_id' is set
        if ('domain_id' not in params or
                params['domain_id'] is None):
            raise ValueError("Missing the required parameter `domain_id` when calling `get_group_members`")  # noqa: E501
        # verify the required parameter 'group_id' is set
        if ('group_id' not in params or
                params['group_id'] is None):
            raise ValueError("Missing the required parameter `group_id` when calling `get_group_members`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'domain_id' in params:
            path_params['domainID'] = params['domain_id']  # noqa: E501
        if 'group_id' in params:
            path_params['groupID'] = params['group_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/{domainID}/groups/{groupID}/roles/members', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='EntityMembersObj',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_group_role(self, domain_id, group_id, **kwargs):  # noqa: E501
        """Retrieves group role.  # noqa: E501

        Retrieves a specific group role that is identified by the role name.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_group_role(domain_id, group_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str domain_id: Unique domain identifier. (required)
        :param str group_id: Unique group identifier. (required)
        :param str role_id: List groups that the user has the given role ID on.
        :return: Role
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_group_role_with_http_info(domain_id, group_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_group_role_with_http_info(domain_id, group_id, **kwargs)  # noqa: E501
            return data

    def get_group_role_with_http_info(self, domain_id, group_id, **kwargs):  # noqa: E501
        """Retrieves group role.  # noqa: E501

        Retrieves a specific group role that is identified by the role name.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_group_role_with_http_info(domain_id, group_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str domain_id: Unique domain identifier. (required)
        :param str group_id: Unique group identifier. (required)
        :param str role_id: List groups that the user has the given role ID on.
        :return: Role
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['domain_id', 'group_id', 'role_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_group_role" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'domain_id' is set
        if ('domain_id' not in params or
                params['domain_id'] is None):
            raise ValueError("Missing the required parameter `domain_id` when calling `get_group_role`")  # noqa: E501
        # verify the required parameter 'group_id' is set
        if ('group_id' not in params or
                params['group_id'] is None):
            raise ValueError("Missing the required parameter `group_id` when calling `get_group_role`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'domain_id' in params:
            path_params['domainID'] = params['domain_id']  # noqa: E501
        if 'group_id' in params:
            path_params['groupID'] = params['group_id']  # noqa: E501

        query_params = []
        if 'role_id' in params:
            query_params.append(('role_id', params['role_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/{domainID}/groups/{groupID}/roles/{roleID}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Role',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def list_available_actions(self, domain_id, **kwargs):  # noqa: E501
        """Retrieves available actions.  # noqa: E501

        Retrieves a list of available actions.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_available_actions(domain_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str domain_id: Unique domain identifier. (required)
        :return: AvailableActionsObj
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.list_available_actions_with_http_info(domain_id, **kwargs)  # noqa: E501
        else:
            (data) = self.list_available_actions_with_http_info(domain_id, **kwargs)  # noqa: E501
            return data

    def list_available_actions_with_http_info(self, domain_id, **kwargs):  # noqa: E501
        """Retrieves available actions.  # noqa: E501

        Retrieves a list of available actions.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_available_actions_with_http_info(domain_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str domain_id: Unique domain identifier. (required)
        :return: AvailableActionsObj
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['domain_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method list_available_actions" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'domain_id' is set
        if ('domain_id' not in params or
                params['domain_id'] is None):
            raise ValueError("Missing the required parameter `domain_id` when calling `list_available_actions`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'domain_id' in params:
            path_params['domainID'] = params['domain_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/{domainID}/groups/roles/available-actions', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='AvailableActionsObj',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def list_group_role_actions(self, domain_id, group_id, **kwargs):  # noqa: E501
        """Lists group role actions.  # noqa: E501

        Retrieves a list of group role actions.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_group_role_actions(domain_id, group_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str domain_id: Unique domain identifier. (required)
        :param str group_id: Unique group identifier. (required)
        :param str role_id: List groups that the user has the given role ID on.
        :return: RoleActionsObj
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.list_group_role_actions_with_http_info(domain_id, group_id, **kwargs)  # noqa: E501
        else:
            (data) = self.list_group_role_actions_with_http_info(domain_id, group_id, **kwargs)  # noqa: E501
            return data

    def list_group_role_actions_with_http_info(self, domain_id, group_id, **kwargs):  # noqa: E501
        """Lists group role actions.  # noqa: E501

        Retrieves a list of group role actions.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_group_role_actions_with_http_info(domain_id, group_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str domain_id: Unique domain identifier. (required)
        :param str group_id: Unique group identifier. (required)
        :param str role_id: List groups that the user has the given role ID on.
        :return: RoleActionsObj
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['domain_id', 'group_id', 'role_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method list_group_role_actions" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'domain_id' is set
        if ('domain_id' not in params or
                params['domain_id'] is None):
            raise ValueError("Missing the required parameter `domain_id` when calling `list_group_role_actions`")  # noqa: E501
        # verify the required parameter 'group_id' is set
        if ('group_id' not in params or
                params['group_id'] is None):
            raise ValueError("Missing the required parameter `group_id` when calling `list_group_role_actions`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'domain_id' in params:
            path_params['domainID'] = params['domain_id']  # noqa: E501
        if 'group_id' in params:
            path_params['groupID'] = params['group_id']  # noqa: E501

        query_params = []
        if 'role_id' in params:
            query_params.append(('role_id', params['role_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/{domainID}/groups/{groupID}/roles/{roleID}/actions', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='RoleActionsObj',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def list_group_role_members(self, domain_id, group_id, **kwargs):  # noqa: E501
        """Lists group role members.  # noqa: E501

        Retrieves a list of group role members.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_group_role_members(domain_id, group_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str domain_id: Unique domain identifier. (required)
        :param str group_id: Unique group identifier. (required)
        :param str role_id: List groups that the user has the given role ID on.
        :return: RoleMembersObj
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.list_group_role_members_with_http_info(domain_id, group_id, **kwargs)  # noqa: E501
        else:
            (data) = self.list_group_role_members_with_http_info(domain_id, group_id, **kwargs)  # noqa: E501
            return data

    def list_group_role_members_with_http_info(self, domain_id, group_id, **kwargs):  # noqa: E501
        """Lists group role members.  # noqa: E501

        Retrieves a list of group role members.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_group_role_members_with_http_info(domain_id, group_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str domain_id: Unique domain identifier. (required)
        :param str group_id: Unique group identifier. (required)
        :param str role_id: List groups that the user has the given role ID on.
        :return: RoleMembersObj
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['domain_id', 'group_id', 'role_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method list_group_role_members" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'domain_id' is set
        if ('domain_id' not in params or
                params['domain_id'] is None):
            raise ValueError("Missing the required parameter `domain_id` when calling `list_group_role_members`")  # noqa: E501
        # verify the required parameter 'group_id' is set
        if ('group_id' not in params or
                params['group_id'] is None):
            raise ValueError("Missing the required parameter `group_id` when calling `list_group_role_members`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'domain_id' in params:
            path_params['domainID'] = params['domain_id']  # noqa: E501
        if 'group_id' in params:
            path_params['groupID'] = params['group_id']  # noqa: E501

        query_params = []
        if 'role_id' in params:
            query_params.append(('role_id', params['role_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/{domainID}/groups/{groupID}/roles/{roleID}/members', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='RoleMembersObj',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def list_group_roles(self, domain_id, group_id, **kwargs):  # noqa: E501
        """Retrieves groups roles.  # noqa: E501

        Retrieves a list of group roles. Due to performance concerns, data is retrieved in subsets. The API groups must ensure that the entire dataset is consumed either by making subsequent requests, or by increasing the subset size of the initial request.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_group_roles(domain_id, group_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str domain_id: Unique domain identifier. (required)
        :param str group_id: Unique group identifier. (required)
        :param int limit: Size of the subset to retrieve.
        :param int offset: Number of items to skip during retrieval.
        :return: RolesPage
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.list_group_roles_with_http_info(domain_id, group_id, **kwargs)  # noqa: E501
        else:
            (data) = self.list_group_roles_with_http_info(domain_id, group_id, **kwargs)  # noqa: E501
            return data

    def list_group_roles_with_http_info(self, domain_id, group_id, **kwargs):  # noqa: E501
        """Retrieves groups roles.  # noqa: E501

        Retrieves a list of group roles. Due to performance concerns, data is retrieved in subsets. The API groups must ensure that the entire dataset is consumed either by making subsequent requests, or by increasing the subset size of the initial request.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_group_roles_with_http_info(domain_id, group_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str domain_id: Unique domain identifier. (required)
        :param str group_id: Unique group identifier. (required)
        :param int limit: Size of the subset to retrieve.
        :param int offset: Number of items to skip during retrieval.
        :return: RolesPage
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['domain_id', 'group_id', 'limit', 'offset']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method list_group_roles" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'domain_id' is set
        if ('domain_id' not in params or
                params['domain_id'] is None):
            raise ValueError("Missing the required parameter `domain_id` when calling `list_group_roles`")  # noqa: E501
        # verify the required parameter 'group_id' is set
        if ('group_id' not in params or
                params['group_id'] is None):
            raise ValueError("Missing the required parameter `group_id` when calling `list_group_roles`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'domain_id' in params:
            path_params['domainID'] = params['domain_id']  # noqa: E501
        if 'group_id' in params:
            path_params['groupID'] = params['group_id']  # noqa: E501

        query_params = []
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501
        if 'offset' in params:
            query_params.append(('offset', params['offset']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/{domainID}/groups/{groupID}/roles', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='RolesPage',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_group_role(self, body, domain_id, group_id, **kwargs):  # noqa: E501
        """Updates group role.  # noqa: E501

        Updates a specific group role that is identified by the role name.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_group_role(body, domain_id, group_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param UpdateRoleObj body: JSON- formatted object decsribing a role to be updated. (required)
        :param str domain_id: Unique domain identifier. (required)
        :param str group_id: Unique group identifier. (required)
        :param str role_id: List groups that the user has the given role ID on.
        :return: Role
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.update_group_role_with_http_info(body, domain_id, group_id, **kwargs)  # noqa: E501
        else:
            (data) = self.update_group_role_with_http_info(body, domain_id, group_id, **kwargs)  # noqa: E501
            return data

    def update_group_role_with_http_info(self, body, domain_id, group_id, **kwargs):  # noqa: E501
        """Updates group role.  # noqa: E501

        Updates a specific group role that is identified by the role name.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_group_role_with_http_info(body, domain_id, group_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param UpdateRoleObj body: JSON- formatted object decsribing a role to be updated. (required)
        :param str domain_id: Unique domain identifier. (required)
        :param str group_id: Unique group identifier. (required)
        :param str role_id: List groups that the user has the given role ID on.
        :return: Role
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'domain_id', 'group_id', 'role_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_group_role" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `update_group_role`")  # noqa: E501
        # verify the required parameter 'domain_id' is set
        if ('domain_id' not in params or
                params['domain_id'] is None):
            raise ValueError("Missing the required parameter `domain_id` when calling `update_group_role`")  # noqa: E501
        # verify the required parameter 'group_id' is set
        if ('group_id' not in params or
                params['group_id'] is None):
            raise ValueError("Missing the required parameter `group_id` when calling `update_group_role`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'domain_id' in params:
            path_params['domainID'] = params['domain_id']  # noqa: E501
        if 'group_id' in params:
            path_params['groupID'] = params['group_id']  # noqa: E501

        query_params = []
        if 'role_id' in params:
            query_params.append(('role_id', params['role_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/{domainID}/groups/{groupID}/roles/{roleID}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Role',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
