# coding: utf-8

"""
    SuperMQ Channels Service

    This is the Channels Server based on the OpenAPI 3.0 specification.  It is the HTTP API for managing platform channels. You can now help us improve the API whether it's by making changes to the definition itself or to the code. Some useful links: - [The SuperMQ repository](https://github.com/absmach/supermq)   # noqa: E501

    OpenAPI spec version: 0.18.0
    Contact: info@abstractmachines.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ChannelReqObj(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'parent_id': 'str',
        'route': 'str',
        'metadata': 'object',
        'status': 'str'
    }

    attribute_map = {
        'name': 'name',
        'parent_id': 'parent_id',
        'route': 'route',
        'metadata': 'metadata',
        'status': 'status'
    }

    def __init__(self, name=None, parent_id=None, route=None, metadata=None, status=None):  # noqa: E501
        """ChannelReqObj - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._parent_id = None
        self._route = None
        self._metadata = None
        self._status = None
        self.discriminator = None
        self.name = name
        if parent_id is not None:
            self.parent_id = parent_id
        if route is not None:
            self.route = route
        if metadata is not None:
            self.metadata = metadata
        if status is not None:
            self.status = status

    @property
    def name(self):
        """Gets the name of this ChannelReqObj.  # noqa: E501

        Free-form channel name. Channel name is unique on the given hierarchy level.  # noqa: E501

        :return: The name of this ChannelReqObj.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ChannelReqObj.

        Free-form channel name. Channel name is unique on the given hierarchy level.  # noqa: E501

        :param name: The name of this ChannelReqObj.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def parent_id(self):
        """Gets the parent_id of this ChannelReqObj.  # noqa: E501

        Id of parent channel, it must be existing channel.  # noqa: E501

        :return: The parent_id of this ChannelReqObj.  # noqa: E501
        :rtype: str
        """
        return self._parent_id

    @parent_id.setter
    def parent_id(self, parent_id):
        """Sets the parent_id of this ChannelReqObj.

        Id of parent channel, it must be existing channel.  # noqa: E501

        :param parent_id: The parent_id of this ChannelReqObj.  # noqa: E501
        :type: str
        """

        self._parent_id = parent_id

    @property
    def route(self):
        """Gets the route of this ChannelReqObj.  # noqa: E501

        Channel route.  # noqa: E501

        :return: The route of this ChannelReqObj.  # noqa: E501
        :rtype: str
        """
        return self._route

    @route.setter
    def route(self, route):
        """Sets the route of this ChannelReqObj.

        Channel route.  # noqa: E501

        :param route: The route of this ChannelReqObj.  # noqa: E501
        :type: str
        """

        self._route = route

    @property
    def metadata(self):
        """Gets the metadata of this ChannelReqObj.  # noqa: E501

        Arbitrary, object-encoded channels's data.  # noqa: E501

        :return: The metadata of this ChannelReqObj.  # noqa: E501
        :rtype: object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this ChannelReqObj.

        Arbitrary, object-encoded channels's data.  # noqa: E501

        :param metadata: The metadata of this ChannelReqObj.  # noqa: E501
        :type: object
        """

        self._metadata = metadata

    @property
    def status(self):
        """Gets the status of this ChannelReqObj.  # noqa: E501

        Channel Status  # noqa: E501

        :return: The status of this ChannelReqObj.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ChannelReqObj.

        Channel Status  # noqa: E501

        :param status: The status of this ChannelReqObj.  # noqa: E501
        :type: str
        """

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ChannelReqObj, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChannelReqObj):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
