# coding: utf-8

# flake8: noqa

"""
    Magistrala Alarms API

    HTTP API for managing alarms service. Some useful links: - [The Magistrala repository](https://github.com/absmach/magistrala)   # noqa: E501

    OpenAPI spec version: 0.15.1
    Contact: info@abstractmachines.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.alarms_api import AlarmsApi
from swagger_client.api.health_api import HealthApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.alarm import Alarm
from swagger_client.models.alarms_page import AlarmsPage
from swagger_client.models.health_info import HealthInfo
