# coding: utf-8

# flake8: noqa
"""
    SuperMQ Clients Service

    This is the Clients Server based on the OpenAPI 3.0 specification.  It is the HTTP API for managing platform clients. You can now help us improve the API whether it's by making changes to the definition itself or to the code. Some useful links: - [The SuperMQ repository](https://github.com/absmach/supermq)   # noqa: E501

    OpenAPI spec version: 0.18.0
    Contact: info@abstractmachines.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.available_actions_obj import AvailableActionsObj
from swagger_client.models.client import Client
from swagger_client.models.client_credentials import ClientCredentials
from swagger_client.models.client_req_obj import ClientReqObj
from swagger_client.models.client_req_obj_credentials import ClientReqObjCredentials
from swagger_client.models.client_secret import ClientSecret
from swagger_client.models.client_tags import ClientTags
from swagger_client.models.client_update import ClientUpdate
from swagger_client.models.client_with_empty_secret import ClientWithEmptySecret
from swagger_client.models.client_with_empty_secret_credentials import ClientWithEmptySecretCredentials
from swagger_client.models.clients_page import ClientsPage
from swagger_client.models.create_role_obj import CreateRoleObj
from swagger_client.models.entity_members_obj import EntityMembersObj
from swagger_client.models.entity_members_obj_members import EntityMembersObjMembers
from swagger_client.models.entity_members_obj_roles import EntityMembersObjRoles
from swagger_client.models.error import Error
from swagger_client.models.health_res import HealthRes
from swagger_client.models.new_role import NewRole
from swagger_client.models.parent_group_req_obj import ParentGroupReqObj
from swagger_client.models.role import Role
from swagger_client.models.role_actions_obj import RoleActionsObj
from swagger_client.models.role_members_obj import RoleMembersObj
from swagger_client.models.roles_page import RolesPage
from swagger_client.models.update_role_obj import UpdateRoleObj
